language: node_js

node_js:
  - "7.2"

script: 
  - node --version

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 93392801a1213084689b421a0d86bc0521335389
  keep-history: true
  on:
    branch: master
