language: node_js

node_js:
  - "7.2"

script: 
  - node --version

deploy:
  provider: pages
  skip-cleanup: true
  github-token: dcf385d194d03ce1389f8411fc9d367469b491ef
  keep-history: true
  on:
    branch: master
