language: node_js

node_js:
  - "7.2"

script: 
  - node --version

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: dist
  keep-history: true
  on:
    branch: master

git:
  depth: 10
