language: node_js

node_js:
  - "7.2"

script: 
  - node --version

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ab89b6796d19107b26f49d336ab33d4e7611f148
  keep-history: true
  on:
    branch: master

git:
  depth: 3
